### ISSUE TITLE
How to mock in Jest?

### ISSUE THREAD

**Issue by paambaati** [WebEngage/react-native-webengage#11]
I can't for the life of me successfully mock `react-native-webengage` in Jest. I notice that the library itself doesn't have tests. Is there a working example somewhere that shows how to mock this package?

Things I've tried - 

1. Manual mocking.
2. `jest.genMockFromModule("react-native-webengage")`
3. ES6 Class mocking (based on the Jest docs for it).

**Comment by paambaati** [comment]
For anyone that stumbled on to this issue, here's how I was able to mock `react-native-webengage` in Jest.

```javascript
jest.mock("react-native-webengage", () => {
  return function() {
    return {
      init: jest.fn(),
      track: jest.fn(),
      screen: jest.fn(),
      user: {
        login: jest.fn(),
        setAttribute: jest.fn(),
      }
    };
  };
});
```

Most of the trouble was around getting ES6 Class-style default exports to play nicely with Jest's mocking.

**Comment by ygit** [comment]
Good to see that you resolved your own issue @paambaati 👍
