### ISSUE TITLE
Push Notification Android

### ISSUE THREAD

**Issue by jitish2** [WebEngage/react-native-webengage#15]
In react native android - Webengage methods are not being called after receiving notification (onPrepare, onShown, onDismiss and onClick.)

Only webengage.push.onClick is called
Can anyone help me out of this issue.

**Comment by akshay-engage** [comment]
Thank you for your inquiry. We're delighted to inform you that our push notification methods are fully functional for both Android and iOS platforms. To gain a comprehensive understanding and access detailed information, we recommend referring to the following resources:

* Sample Application: You can explore practical usage examples in our [sample application on GitHub](https://github.com/WebEngage/react-native-webengage/tree/develop/ExampleApp).

* Official Documentation: For comprehensive guidance, please consult our [official documentation on React Native push messaging](https://docs.webengage.com/docs/react-native-push-messaging).

These resources will provide you with the necessary insights and instructions to effectively utilize push notification methods in your projects.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
