### ISSUE TITLE
advertisingIdentifier: reason for apple rejection. 

### ISSUE THREAD

**Issue by Siddhant-Goswami** [WebEngage/react-native-webengage#21]
I'm using this configuration :

react-native: 0.63.3
react-native-webengage: 1.2.7
Apple rejects our application with the following message:

your Kids Category app collects IDFA information, which is not appropriate.

and to test if our application is using IDFA in some plugin, I executed the following command:

fgrep -R advertisingIdentifier .

which retrieve this:

Pods/WebEngage/xc11/WebEngage.framework/WebEngage

is there any way to remove the reference to IDFA? or, is absolutely necessary for this plugin to have that in order to run?

This is currently blocking us from delivering any of our updates to the store.

**Comment by akshay-engage** [comment]
The issue you reported has been resolved through an iOS update quite some time ago. Users should no longer encounter this problem.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
