### ISSUE TITLE
Update targetSdkVersion and buildToolsVersion

### ISSUE THREAD

**Issue by haruelrovix** [WebEngage/react-native-webengage#24]
Hi WebEngage team 👋🏻 

Is there any roadmap on your end to support newest Android version?

> The specified Android SDK Build Tools version (28.0.3) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.0.

https://github.com/WebEngage/react-native-webengage/blob/master/lib/android/build.gradle#L21

**Comment by akshay-engage** [comment]
We are pleased to inform you that our library now supports the latest SDK version with a minimum SDK version of 21 and a target SDK version of 33. This addresses the concern raised in this issue. As a result, we are closing this issue.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
