### ISSUE TITLE
[Android] AAPT: error: resource android:attr/lStar not found.

### ISSUE THREAD

**Issue by wiedzmin26** [WebEngage/react-native-webengage#31]
Hi,
Trying to run the code in the release mode in simulator, but getting this error ->
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDevDebugResources'.
> Android resource linking failed
  /Users/admin/.gradle/caches/transforms-2/files-2.1/177721085d422c8ab0578015b8a1178f/res/values/values.xml:2422:5-2449:25: AAPT: error: resource android:attr/lStar not found.
      
  error: failed linking references.
![Zrzut ekranu 2021-12-9 o 12 44 17](https://user-images.githubusercontent.com/52349575/145390592-647665c0-40a7-46fc-aceb-cd47f0aad95d.png)

I'm using this configuration :
react-native: 0.61.4
react-native-webengage: 1.2.10

**Comment by SarthakWebEngage** [comment]
Hi @wiedzmin26,
This issue has been fixed from our end, kindly clean the cache for Android and build it again, and make sure that it uses webengage native android SDK (com.webengage:android-sdk:3.18.9) version from maven.
