### ISSUE TITLE
how we can integrate webengage with use_frameworks?

### ISSUE THREAD

**Issue by karthikmandava7** [WebEngage/react-native-webengage#41]
As we have other dependencies so we are using use_frameworks, but with this Push notifications are not working properly is there any other solution for this?

**Comment by akshay-engage** [comment]
For detailed instructions on integrating WebEngage into your iOS project using use_frameworks, please refer to our official documentation: [WebEngage iOS Integration Documentation](https://docs.webengage.com/docs/ios-push-messaging#:~:text=Solution%202%20(use_frameworks!))

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
