### ISSUE TITLE
Support for new architecture

### ISSUE THREAD

**Issue by antilakash** [WebEngage/react-native-webengage#44]

**Comment by akshay-engage** [comment]
WebEngage library now fully supports React Native version up to 0.72 Whether you prefer to use the newArchitecture mode enabled or disabled, our library is designed to provide a seamless experience. Feel free to update to the latest version of React Native and explore the newArchitecture mode with confidence, knowing that our library has you covered.

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries."
