### ISSUE TITLE
 'react/rctbundleurlprovider.h' file not found 

### ISSUE THREAD

**Issue by alifarajj** [WebEngage/react-native-webengage#45]
I use latest version of  "react-native-webengage"  with RN 0.64 and getting error 'react/rctbundleurlprovider.h' file not found

**Comment by akshay-engage** [comment]
**Version Compatibility Update:** 

The issue you've come across does appear to be tied to version compatibility

For React Native versions less than 0.68, it is recommended to use WebEngage version v1.2.12.
For React Native versions greater than or equal to 0.68, we advise using WebEngage version v1.3.0 for optimal compatibility. 

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
