### ISSUE TITLE
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.

### ISSUE THREAD

**Issue by Commaando** [WebEngage/react-native-webengage#46]
I get this warning console logged several times on webengage.track() method.

**Comment by Commaando** [comment]
rn version: 0.68
react version: 17.0.2

**Comment by roli-agrawal** [comment]
any update

**Comment by akshay-engage** [comment]
This issue is fixed in our latest version. Please update to the latest version. Closing this issue now
