### ISSUE TITLE
Not able run project in React-native iOS 

### ISSUE THREAD

**Issue by savithrielangovan** [WebEngage/react-native-webengage#47]
**Xcode version  :** Version 13.1 (13A1030d)
 **npm version** : "react-native-webengage": "^1.3.0",
react-native-cli: 2.0.1
react-native: 0.63.3

Description :
No visible @interface for 'RCTBundleURLProvider' declares the selector 'jsBundleURLForBundleRoot:'
<img width="1440" alt="Screenshot 2023-01-20 at 6 15 08 PM" src="https://user-images.githubusercontent.com/85921630/213697972-24aa77ac-3bd9-45f8-a309-875dd8fdeff5.png">

**Comment by pkpardeep482** [comment]
facing same issue

**Comment by trung1051996** [comment]
same this issue

**Comment by nguyenthanhtrung1996** [comment]
Go to WEGWebEngageBridge.m file of react-native-webengage:
Path: **yourPJ**/node_modules/react-native-webengage/ios/WEGWebEngageBridge.m
Here's the Fix:
**Replace:**
return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
**With:**
return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];

Re-Build the app and you are good to go.

**Comment by supmanyu** [comment]
the fix mentioned by @nguyenthanhtrung1996 works on react-native version 0.64.3. Thanks!

**Comment by akshay-engage** [comment]
**Version Compatibility Update:** 

The issue you've come across does appear to be tied to version compatibility 

For React Native versions less than 0.68, it is recommended to use WebEngage version v1.2.12. 
For React Native versions greater than or equal to 0.68, we advise using WebEngage version v1.3.0 for optimal compatibility. 

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
