### ISSUE TITLE
Issue with play-services-ads:15.0.1 Dependency - Deprecated SDK Version

### ISSUE THREAD

**Issue by mansilaad** [WebEngage/react-native-webengage#53]
Hello maintainers and community,

I've integrated react-native-webengage into my React Native application and followed the documentation which guided me to add the following dependency:

dependencies {
    implementation 'com.google.android.gms:play-services-ads:15.0.1'
}

However, when I attempt to publish my app to the Google Play Store, I receive an error indicating that the play-services-ads:15.0.1 SDK version is deprecated. The exact message from the Play Store console is as follows:

**Upgrade to a newer com.google.android.gms SDK version
The SDK developer com.google.android.gms has added a note for play-services-ads:15.0.1. Here's what the SDK developer told us:
This version is officially deprecated, and will soon disable ad loading. Please update to a new version. See https://developers.google.com/admob/android/deprecation for more details.
If you do not upgrade to a newer version, you may not be able to release future versions of your app with this SDK.**

Here are some details about my environment:

"react": "18.2.0",
"react-native": "0.70.5",
"react-native-webengage": "^1.3.0",
Targeted platform: android
Android studio version - Android Studio Giraffe | 2022.3.1

Output of react-native info- 
System:
    OS: macOS 13.4.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 19.37 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.12.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.4, iOS 16.4, macOS 13.3, tvOS 16.4, watchOS 9.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.3 AI-223.8836.35.2231.10406996
    Xcode: 14.3.1/14E300c - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.5 => 0.70.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Given the above, I wanted to bring this to your attention and inquire if there are plans to update the dependency in the near future. Using a deprecated SDK version could potentially affect many users who rely on react-native-webengage for their applications.

Thank you for your time and assistance. Looking forward to a resolution.

**Comment by akshay-engage** [comment]
Hi @mansilaad ,

For the most up-to-date information on advertising ID tracking in our library, we recommend referring to our latest documentation. You can find detailed guidance in the following link:

[Latest Advertising ID Tracking Documentation](https://docs.webengage.com/docs/android-getting-started#advertising-id-tracking)

Our documentation provides the most current instructions and best practices for implementing advertising ID tracking in your Android project.

If you have any further questions or encounter any issues, please feel free to reach out to our dedicated support team at [support@webengage.com](mailto:support@webengage.com). We're here to assist you and ensure a smooth experience.
