### ISSUE TITLE
Expo support?

### ISSUE THREAD

**Issue by singhayush1403** [WebEngage/react-native-webengage#55]
Does this library support expo out of the box? Or will I have to write my own config plugins. Couldn't find it anywhere in the documentation

**Comment by akshay-engage** [comment]
Hi @singhayush1403,

The WebEngage library can work with Expo applications, but please note that successful WebEngage integration often requires the generation of native code. To ensure a seamless integration with WebEngage, it's essential to generate the necessary native code for your Expo project.


If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.

**Comment by chaitanya71998** [comment]
Hi @singhayush1403 have you integrated webengage with expo app without ejecting?
