### ISSUE TITLE
Rich Notification Support for React Native

### ISSUE THREAD

**Issue by singhayush1403** [WebEngage/react-native-webengage#59]
Does WebEngage support rich push notifications in React Native? I could not find any example code samples to refer to.

**Comment by akshay-engage** [comment]
Hi @singhayush1403 ,

Please refer to our [Sample Application ](https://github.com/WebEngage/react-native-webengage/tree/latestSampleApp) for the example on Rich notificaiton. 
Also, Refer to our [Docs](https://docs.webengage.com/docs/ios-push-messaging). for step by step procedure to integrate WebEngage Rich Push Notification.

If you have any further questions or encounter any issues, please feel free to reach out to our dedicated support team at [support@webengage.com](mailto:support@webengage.com). We're here to assist you and ensure a smooth experience.
