### ISSUE TITLE
Family Policy Violation 

### ISSUE THREAD

**Issue by antilakash** [WebEngage/react-native-webengage#61]
We are on react-native-webengage 1.2.7. My app is for children and I am getting family policy violation GAID rejection because of this. I saw a fix for but it's in version 1.4.1 for which I have to plan a react native upgrade. Any workaround for this. can we get some patch package for GAID.
Rejection Mail From Play Store: For example, the destinations of Android Advertising ID transmission may include, but are not limited to [webengage.com]
@BhaveshWebEngage

**Comment by akshay-engage** [comment]
Hi @antilakash,

We highly recommend upgrading to the latest version of React Native to leverage the [latest changes](https://docs.webengage.com/docs/changelogs-react-native#v141-19-dec-2023) in our SDK.

As a workaround, you can manually update the WebEngage Android SDK version in `app/build.gradle` and `YOUR_APP/node_modules/react-native-webengage/android/build.gradle` to the latest version as follows:
```gradle
api 'com.webengage:android-sdk:4.+'
```

If you have any further questions or encounter any issues, please feel free to reach out to our dedicated support team at [support@webengage.com](mailto:support@webengage.com). We're here to assist you and ensure a smooth experience.
