### ISSUE TITLE
iOS: when adding callback for webengage, app is being killed (unrecognized selector sent to instance)

### ISSUE THREAD

**Issue by imanshul** [WebEngage/react-native-webengage#62]
The following error occur in main for iOS on following instruction to detect click action in iOS:

> Thread 1: "-[WEGWebEngageBridge isLoading]: unrecognized selector sent to instance 0x600002121e00"

Link for callback steps:
https://docs.webengage.com/docs/react-native-callbacks#push-notification-callbacks

AppDelegate.h
```
#import <RCTAppDelegate.h>
#import <UIKit/UIKit.h>
#import <WEGWebEngageBridge.h>

@interface AppDelegate : RCTAppDelegate
@property (nonatomic, strong) WEGWebEngageBridge *bridge;
@end

```
AppDelegate.mm didFinishLaunchingWithOptions

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  self.bridge = [WEGWebEngageBridge new];
    RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self.bridge launchOptions:launchOptions];
    RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge moduleName:@"App13Karat" initialProperties:nil];
  
  //self.moduleName = @"App13Karat";
  // You can add your custom initial props in the dictionary below.
  // They will be passed down to the ViewController used by React Native.
  //self.initialProps = @{};
  
  // Add me --- \/
    [FIRApp configure];
  // Add me --- /\
  
  //Start WebEngage
  self.bridge = [WEGWebEngageBridge new];
  [WebEngage sharedInstance].pushNotificationDelegate = self.bridge;
  [[WebEngage sharedInstance] application:application
              didFinishLaunchingWithOptions:launchOptions notificationDelegate:self.bridge];

  //End WebEngage

  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}
```

React-Native version: 0.73.1
react-native-webengage: 1.4.1

**Comment by akshay-engage** [comment]
Hi @imanshul 

Given that your application integrates both WebEngage and Firebase, we recommend following the [Manual Integration](https://docs.webengage.com/docs/ios-advanced#7-disable-swizzling) steps.

For additional questions or if you face any issues, please don't hesitate to contact our dedicated support team at [support@webengage.com](mailto:support@webengage.com). We're here to help and ensure a seamless experience.

**Comment by imanshul** [comment]
@akshay-engage We have already added Swizzling steps, but when adding code related to callback in didFinishLaunchingWithOptions. The app is crashing, can you please provide latest doc with react-native version 0.73.1

**Comment by akshay-engage** [comment]
Hello @imanshul,

Kindly review our [Sample Application](https://github.com/WebEngage/react-native-webengage/tree/feature/DevSampleApp) that is currently running on the latest version 0.73. This will provide you with valuable insights into the implementation of the callback.

If the issue persists, please feel free to contact us at [support@webengage.com](mailto:support@webengage.com). Our team is ready to assist and debug your code to identify the underlying issue.

**Comment by imanshul** [comment]
When adding code as per sample app, i'm facing crash when received in app notification.

Exception	NSException *	"Error when sending event: notificationPrepared with body: {\n    actions =     (\n                {\n            actionCategory = CTA;\n            actionEId = \"~bc29b893\";\n            actionLink = \"13karat://asd/dashboard\";\n            actionTarget = \"_top\";\n            actionText = \"Bitch!!\";\n            isPrime = 1;\n            sdkId = 3;\n            type = \"DEEP_LINK\";\n        },\n                {\n            actionCategory = CTA;\n            actionEId = \"~b05d855a\";\n            actionLink = \"w://p/open_url_in_browser/13karat%3A%2F%2Fasd%2Fdashboard\";\n            actionTarget = \"_top\";\n            actionText = \"Bitch!!\";\n            isPrime = 1;\n            sdkId = 2;\n            type = \"EXTERNAL_URL\";\n        }\n    );\n    canClose = 1;\n    canMinimize = 1;\n    config =     {\n        backgroundColor = \"rgb(16, 21, 24, 1)\";\n        c2aBackgroundColor = \"#4A90E2\";\n        c2aTextColor = \"#FFFFFF\";\n        c2aTextFont = \"Sans-Serif\";\n        closeIconColor = \"#FFFFFF\";\n        descriptionColor = \"#FFFFFF\";\n    "	0x0000600000d15d10
