### ISSUE TITLE
Invalid tracking information issue when submitting release to appstore

### ISSUE THREAD

**Issue by Abdelwahab313** [WebEngage/react-native-webengage#64]
I have an issue with App store after submitting a release build.

Please correct the following issues and upload a new binary to App Store Connect.

ITMS-91064: Invalid tracking information - A PrivacyInfo.xcprivacy file contains invalid tracking information at the following path: “Frameworks/WebEngage.framework/PrivacyInfo.xcprivacy”. NSPrivacyTracking must be true if NSPrivacyTrackingDomains isn‘t empty. Keys and values in your app’s privacy manifest must be valid. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files.

**Comment by akshay-engage** [comment]
Hi @Abdelwahab313,

Could you please update your WebEngage library to the latest version where we have fixed this issue?

Here are the steps to follow:

1. Clear node_modules
2. Delete ios/pods and ios/Podfile.lock
3. Run npm install
4. Navigate to the iOS directory and install pods: cd ios/ and run pod install

After completing these steps, ensure your Podfile.lock has WebEngage (6.8.1 or above).

If you have any further questions or need assistance with the integration, We're here to help. You can contact us at [support@webengage.com](mailto:support@webengage.com) for any additional queries.
