### ISSUE TITLE
Fcm key upgrade from legacy to http v1

### ISSUE THREAD

**Issue by antilakash** [WebEngage/react-native-webengage#65]
While editing I am not getting option to  change from legacy to http v1 dcm key as stated in docs.
<img width="1325" alt="Screenshot 2024-05-25 at 8 07 56 PM" src="https://github.com/WebEngage/react-native-webengage/assets/111955968/7804287c-8a25-48ce-84ee-5f83e9c339e9">

This is what I see on my dashboard vs what I should see (see attached docs)
https://docs.webengage.com/docs/android-push-messaging

**Comment by akshay-engage** [comment]
Hi @antilakash 

Please reach out to us at [support@webengage.com](mailto:support@webengage.com), and we will guide you through the steps
