### ISSUE TITLE
IOS blank screen issue in react native

### ISSUE THREAD

**Issue by omkarKiranaClub** [WebEngage/react-native-webengage#67]
`#import "AppDelegate.h"
#import <Firebase.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <React/RCTBridge.h>
#import <WebEngage/WebEngage.h>
#import <UserNotifications/UserNotifications.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  [FIRApp configure];
  
  self.moduleName = @"kiranaclub";
  self.weBridge = [WEGWebEngageBridge new];
  self.initialProps = @{};
  [WebEngage sharedInstance].pushNotificationDelegate = self.weBridge;
  
  if (@available(iOS 10.0, *)) {
    [UNUserNotificationCenter currentNotificationCenter].delegate = (id<UNUserNotificationCenterDelegate>)self;
  }
  [[WebEngage sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
  return [super application:application didFinishLaunchingWithOptions:launchOptions];
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions))completionHandler
{
  NSLog(@"center: %@, notification: %@", center, notification);
  
  [WEGManualIntegration userNotificationCenter:center willPresentNotification:notification];
  
  completionHandler(UNNotificationPresentationOptionAlert | UNNotificationPresentationOptionSound | UNNotificationPresentationOptionBadge);
}

- (void)userNotificationCenter:(UNUserNotificationCenter *)center
didReceiveNotificationResponse:(UNNotificationResponse *)response
         withCompletionHandler:(void (^)(void))completionHandler
{
  NSLog(@"center: %@, response: %@", center, response);
  
  [WEGManualIntegration userNotificationCenter:center didReceiveNotificationResponse:response];
  
  completionHandler();
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
  return [self getBundleURL];
}

- (NSURL *)getBundleURL
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index"];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

@end
`

This is my AppDelegate.mm file 
when i comment this code
  [WebEngage sharedInstance].pushNotificationDelegate = self.weBridge;
  
  if (@available(iOS 10.0, *)) {
    [UNUserNotificationCenter currentNotificationCenter].delegate = (id<UNUserNotificationCenterDelegate>)self;
  }
  [[WebEngage sharedInstance] application:application didFinishLaunchingWithOptions:launchOptions];
  the app works fine
  but if i uncomment it and build the app 4/5 times when i open the app a blank screen comes in IOS 
  I have followed the docs for webengage setup in react native [https://docs.webengage.com/docs/ios-getting-started#2-initialize-the-sdk](url)
  any solution @akshay-engage ?

**Comment by akshay-engage** [comment]
Hi @omkarKiranaClub,

Please contact us at [support@webengage.com](mailto:support@webengage.com) for further verification. We'll address this issue promptly.

Thank you.

**Comment by akshay-engage** [comment]
Hi @BharatEdu97 ,
Could you please drop us an email at [support@webengage.com](mailto:support@webengage.com) with the details of your query? Our team will be happy to assist you further.
