### ISSUE TITLE
Getting {"invalidTokenCallback": [Function anonymous], "tokenInvalidateLister": {"remove": [Function remove]} on calling the function

### ISSUE THREAD

**Issue by Gagan-Deogan** [WebEngage/react-native-webengage#68]

**Comment by Gagan-Deogan** [comment]
@AdityaWebEngage please look into this

**Comment by akshay-engage** [comment]
@Gagan-Deogan 

It looks like your license code has SDK-security enabled. For more information about SDK-security and other features, please contact us at [support@webengage.com](mailto:support@webengage.com).
