### ISSUE TITLE
Cannot access com.webengage.sdk.android.callbacks.WESecurityCallback

### ISSUE THREAD

**Issue by Rajarshi39** [WebEngage/react-native-webengage#69]
upgrading react native from 0.68.5 to 0.74.0. Followed every steps from the official react-native upgrade helper. Even the build is successful. But on startup the app is crashing. I checked the logcat and I got this error.

**Comment by MilindWebEngage** [comment]
@Rajarshi39 Can you share a screenshot of the complete logs?

**Comment by Rajarshi39** [comment]
Yes sure @MilindWebEngage 
using gradle 8.6, gradle plugin 8.2.1 and kotlinVersion 1.9.22
![image](https://github.com/user-attachments/assets/436d2ee9-6e5f-42e2-9200-38e1311c417a)
![image](https://github.com/user-attachments/assets/ffb36744-f49a-449d-8f42-378d4022c7ee)

**Comment by Rajarshi39** [comment]
In the official docs, there is a section with webengagebridge. After adding that. in android studio I am getting this error
![image](https://github.com/user-attachments/assets/71432ef9-2682-490b-aff9-bf2a5e24f18e)

<img width="841" alt="Screenshot 2024-08-02 at 2 57 31 PM" src="https://github.com/user-attachments/assets/8de75cc2-38ea-431d-ac06-02e38c8ef78b">

**Comment by Rajarshi39** [comment]
@MilindWebEngage it got fixed. I missed one thing. Just noticed there was this line in the `app/build.gradle` 
`configurations.all { resolutionStrategy { force 'com.webengage:android-sdk:3.20.5' } }`
commented it. Now it works. Sorry for the confusion.
