### ISSUE TITLE
Crash on IOS

### ISSUE THREAD

**Issue by ealimardaniii** [WebEngage/react-native-webengage#71]
I have crash on IOS like below:

[WEG_GUL_AppDelegate-BAA276F7-F0C5-430D-9B1C-22CE25D03411 application:performFetchWithCompletionHandler:]: unrecognized selector sent to instance 0x3028c7200

"react-native-webengage": "^1.5.1"
"react-native": "0.75.4"

**Comment by akshay-engage** [comment]
@ealimardaniii 
To help resolve the issue you're facing, please share the details with our dedicated support team at [support@webengage.com](mailto:support@webengage.com). We're here to help and ensure a seamless experience.
