### ISSUE TITLE
'WebEngage/WebEngage.h' file not found

### ISSUE THREAD

**Issue by uc-asa** [WebEngage/react-native-webengage#8]
I just updated my react native project with RN 0.59.9. After updating its showing `'WebEngage/WebEngage.h' file not found`.

I tried many things but fails.

Team, could you help please with this.

**Comment by ygit** [comment]
@uc-asa Can you share more details on your integration?
Also, can you share your Podfile, Podfile.lock, Package.json, AppDelegate.{h,m} files?

**Comment by ygit** [comment]
@uc-asa Awaiting your reply.

**Comment by ygit** [comment]
@uc-asa We are debugging this, will get back to you shortly.

**Comment by subramanyaRB** [comment]
@ygit, I'm also facing the same issue, I'm using react-native-webengage v1.1.1, react-native v0.59.1

**Comment by Girish2015** [comment]
Facing the same issue. Unable to release updates to our app because of this error. Please resolve it fast.
react-native v0.59.9
react-native-webengage v1.1.1

**Comment by rdickert** [comment]
Could this be a result of an upgrade to xcode 13?

I have a branch on RN 0.59.8 that was building fine, but now does not. It worked before I got xcode 13 as an automatic update. No guarantee this is the cause, but it is known to cause some problems with RN (see [this issue](https://github.com/facebook/react-native/issues/25138)), so perhaps this module is also affected in some way? RN had to release a fix as part of 0.59.9.

**Comment by uc-asa** [comment]
Hey,

I did some hack, I removed the reference of RNWebenage.xcodepro from my project's library and removed RNWebengage.a files from the binary section under build phase and then

pod install
Clean build and rebuild.

Works for me.

**Comment by ygit** [comment]
@rdickert Does the same branch work on Xcode 10 for you?
It has been working fine for us throughout.
Probably the issue is somewhere between the differences in clients & our Build environment i.e. Xcode or Mac version, CocoaPods version, using New or Old Swift Build System, etc

**Comment by rdickert** [comment]
@ygit I downgraded xcode, and the problem persisted, so I went a little deeper. The change that actually broke the branch came when I was merging a large feature branch. It had a merge conflict in package-lock.json, so I was guessing that something happened in a version change when I addressed that. However, a look at the package-lock.json doesn't show a change to webengage. Our package.json has

```
"react-native-webengage": "^1.0.4"
```

and the package-lock for that version shows

```
    "react-native-webengage": {
      "version": "1.0.6",
      "resolved": "https://registry.npmjs.org/react-native-webengage/-/react-native-webengage-1.0.6.tgz",
      "integrity": "sha512-okDpETJPmoKzRv9XbVfuWdDe18g/ULezYjusidaVSsdxztBijGikplQneTwsa+2uFibeYAUvhvrrBgzEN/Mblg=="
    },
```

Unfortunately for this discussion, I learned that we aren't using webengage anymore, so my fix was to remove it altogether, but hopefully this info will help a little.

**Comment by ygit** [comment]
@uc-asa We have released a new version of iOS SDK: *4.9.8*.
Updating to this version should resolve the issue.

**Comment by ygit** [comment]
As mentioned earlier, updating to WebEngage iOS SDK [version 4.9.8 or above](https://docs.webengage.com/docs/changelogs-ios) resolves this issue.

**Comment by sagar-tomar-groww** [comment]
Try updating to XCode14. Solved the issue for us. 
JFI, XCode14 needs ENABLE_BITCODE = NO
