### ISSUE TITLE
 <Error>: assertion failed: 18F203 16E226: libxpc.dylib getting this error when using pod FirebaseMessaging in iOS

### ISSUE THREAD

**Issue by DarshitaGoMmt** [WebEngage/react-native-webengage#9]
App is crashing on load on adding FirebaseMessaging for iOS.

To reproduce from ExampleApp:
1. Add FirebaseMessaging in Podfile:
```
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
```

2. Add the following lines in AppDelegate.m:
```
#import <Firebase.h>


  [FIRApp configure];
```

3. Run the react-native app for ios after updating pod:
```
pod install 
react-native run-ios
```

Monitor react-native log-ios to get this error
```
Sep 11 12:21:20 go-mac-darshita ExampleApp[58400] <Error>: assertion failed: 18F203 16E226: libxpc.dylib + 80700 [B558DAD6-9E08-3208-B352-1CA4137B67C8]: 0x7d
Sep 11 12:21:20 go-mac-darshita Unknown[58400] <Error>: 
Sep 11 12:21:20 go-mac-darshita com.apple.CoreSimulator.SimDevice.9DF1B234-3BCE-4F5A-B29E-04CB9F347D8A[57091] (UIKitApplication:com.webengage.reactnative[0xaed8][57116][58400]) <Notice>: Service exited due to SIGABRT
Sep 11 12:21:22 go-mac-darshita com.apple.CoreSimulator.SimDevice.9DF1B234-3BCE-4F5A-B29E-04CB9F347D8A[57091] (com.apple.securityuploadd) <Notice>: Service only ran for 5 seconds. Pushing respawn out by 5 seconds.
```

**Comment by ygit** [comment]
@DarshitaGoMmt Please implement the Steps as mentioned in [Disable Swizzling section].(https://docs.webengage.com/docs/ios-advanced#section-7-disable-swizzling)

**Comment by ygit** [comment]
@DarshitaGoMmt Awaiting your reply.

**Comment by DarshitaGoMmt** [comment]
@ygit Thanks a lot for your prompt reply.
But I'm looking for solution for react-native app, which requires changes to be done in AppDelegate.m. Above link shared has disabling in AppDelegate.swift file.
I couldn't find anything for the same in here: https://docs.webengage.com/docs/react-native-advanced#section-ios

**Comment by DarshitaGoMmt** [comment]
@ygit  Thanks for your prompt reply.
Build got fixed and app is not crashing as well.
Will test web engage notification now

**Comment by DarshitaGoMmt** [comment]
Thanks it's working now! :)
